name: Build and deploy

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Package
      run: dotnet publish --configuration Release
    
    - name: Save build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: api-app
        path: .\bin\Release\netcoreapp3.0\publish
        
  deploy:
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: api-app
      
      - name: Create App_offline.htm to stop AspNetModule on server
        uses: neumannalex/app-offline-action@master
        env:
          APP_STATE: offline
          FTP_SERVER: access793420076.webspace-data.io
          FTP_USERNAME: u98144824
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: api
      
      - name: Publish to Webserver
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: access793420076.webspace-data.io
          FTP_USERNAME: u98144824
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: api-app
          REMOTE_DIR: api

      - name: Remove App_offline.htm from server to restart AspNetModule
        uses: neumannalex/app-offline-action@master
        env:
          APP_STATE: online
          FTP_SERVER: access793420076.webspace-data.io
          FTP_USERNAME: u98144824
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: api
